version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
    expose:
      - "5433"
    command: -p 5433
    env_file:
      - ./.env

  backend:
    image: dodge0000/foodgram:v.0.1
    restart: always
    volumes:
      - static_value:/app/backend-static/
      - media_value:/app/backend-media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - media_value:/var/html/backend-media/
      - static_value:/var/html/backend-static/

    depends_on:
      - backend

volumes:
  static_value:
  media_value:
