# Generated by Django 3.2 on 2023-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='backend-media/recipes/images/', verbose_name='Фото блюда'),
        ),
    ]
