# Generated by Django 3.2 on 2023-03-18 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230317_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttorecipe',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, 'Количество должно быть числом более 1')]),
        ),
    ]
