# Generated by Django 3.2 on 2023-03-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230318_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
    ]
